### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by piroyuki666** [piroyuki666/furima-38024#22]
# URL
https://furima-38024.herokuapp.com/
# Basic認証のIDとパスワード
ID : piromin
PASS : 6666
# 出品者用のメールアドレスとパスワード
hiromin@testmail.com
test77
# 購入者用のメールアドレスとパスワード
hiroyu@testmail.com
test88

**Comment by shodai-ito** [comment]
@piroyuki666 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
`商品編集機能`
- [x] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
他人の商品編集ページへ遷移できてしまいます。

`商品購入機能`
- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
都道府県の情報がなくても購入できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by piroyuki666** [comment]
コメントありがとうございます。修正箇所の確認終わりました。再度のフォーム提出をしましたのでご確認をお願い致します。

**Comment by shodai-ito** [comment]
@piroyuki666 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題LGTM](https://user-images.githubusercontent.com/62537107/172522358-8c50dee6-d241-4311-9161-b08de0178709.png)

**Comment by piroyuki666** [comment]
有難うございます。これからも学ぶ姿勢、向上心を大切にエンジニアとして進んでいこうと思います。
